name: assignment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0-132.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.4
  bloc: ^8.1.2
  build_runner: ^2.4.8
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  parse_server_sdk_flutter: ^7.0.1
  sqflite: ^2.3.2
  path: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/fonts/


  fonts:
    - family: Compact
      fonts:
        - asset: assets/fonts/sf_compact_display_light.ttf
          weight: 300
        - asset: assets/fonts/sf_compact_display_regular.ttf
          weight: 400
        - asset: assets/fonts/sf_compact_display_medium.ttf
          weight: 500
        - asset: assets/fonts/sf_compact_display_semibold.otf
          weight: 600
        - asset: assets/fonts/sf_compact_display_bold.ttf
          weight: 700

